# Generated by Django 5.2.3 on 2025-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
