# Generated by Django 5.2.3 on 2025-06-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patientdoctormapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='api.patient'),
        ),
    ]
